2019/10/21 16:29:34    send_main.py    91    INFO -->  返回结果:{'code': 'BI_SUS-200', 'data': {'accountId': 10, 'createTime': 1571646572000, 'id': 3, 'remark': '测试回调1', 'type': 1, 'url': 'http://192.168.12.38:88'}, 'message': '操作成功', 'result': 1}
2019/10/21 16:29:34    send_main.py    111    INFO -->  预期接口返回结果与实际接口返回结果进行对比，对比结果是False
2019/10/21 16:29:34    send_main.py    138    ERROR -->  将结果写入数据库，结果为fail，case_id为bs23_callbackInfo_001
